# Generated by Django 6.0.4 on 2026-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Yillar soni')),
                ('education', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('patients', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('work_schedule', models.JSONField(default=dict)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
