# Generated by Django 5.2.13 on 2026-04-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
